### ISSUE TITLE
dimension error at run_DMN.py:266

### ISSUE THREAD

**Issue by singleheart** [swstarlab/DynamicMemoryNetworks#1]
ipython ./run_DMN.py 실행시 아래와 같이 update_val의 타입이 shared_var의 타입과 맞지 않다는 에러가 발생합니다. 32비트를 써야 하는데 64비트를 써서 그런 것 같은데요. 환경 설정을 따로 해 주어야 하는 것이 있는지 아니면 코드를 수정해야 하는지 여쭙습니다.

환경은 MacOS El Capitan, 
python 2.7.11, Theano 0.9.0dev2, Lasagne 0.2.dev1
입니다. GPU는 사용하지 않고 않습니다. 

---

TypeError                                 Traceback (most recent call last)
/Users/singleheart/work/DynamicMemoryNetworks/run_DMN.py in <module>()
    264                                 dmn.word_dropout_var],
    265                                loss_pretrain,
--> 266                                updates=updates_pretrain)
    267
    268 gate_val_fn = theano.function([dmn.input_var,

/usr/local/lib/python2.7/site-packages/theano/compile/function.pyc in function(inputs, outputs, mode, updates, givens, no_default_updates, accept_inplace, name, rebuild_strict, allow_input_downcast, profile, on_unused_input)
    320                    on_unused_input=on_unused_input,
    321                    profile=profile,
--> 322                    output_keys=output_keys)
    323     # We need to add the flag check_aliased inputs if we have any mutable or
    324     # borrowed used defined inputs

/usr/local/lib/python2.7/site-packages/theano/compile/pfunc.pyc in pfunc(params, outputs, mode, updates, givens, no_default_updates, accept_inplace, name, rebuild_strict, allow_input_downcast, profile, on_unused_input, output_keys)
    441                                          rebuild_strict=rebuild_strict,
    442                                          copy_inputs_over=True,
--> 443                                          no_default_updates=no_default_updates)
    444     # extracting the arguments
    445     input_variables, cloned_extended_outputs, other_stuff = output_vars

/usr/local/lib/python2.7/site-packages/theano/compile/pfunc.pyc in rebuild_collect_shared(outputs, inputs, replace, updates, rebuild_strict, copy_inputs_over, no_default_updates)
    206                        ' function to remove broadcastable dimensions.')
    207
--> 208             raise TypeError(err_msg, err_sug)
    209         assert update_val.type == store_into.type
    210

TypeError: ('An update must have the same type as the original shared variable (shared_var=<TensorType(float32, matrix)>, shared_var.type=TensorType(float32, matrix), update_val=Elemwise{add,no_inplace}.0, update_val.type=TensorType(float64, matrix)).', 'If the difference is related to the broadcast pattern, you can call the tensor.unbroadcast(var, axis_to_unbroadcast[, ...]) function to remove broadcastable dimensions.')

**Comment by dshan4585** [comment]
I assume that this problem is due to data type (dtype) mismatch. In the source code, I used Theano's data type as float32, and it seems you are using float64. You should change dtype setting to "floatX = float32" in "$HOME/.theanorc" of your system. For additional information, you can check http://deeplearning.net/software/theano/library/config.html.

**Comment by singleheart** [comment]
It works! I've got the same result as described in run_DMN.ipynb. Thank you very much.
